language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '5.0'
- iojs
sudo: false
after_script: npm install codecov.io && cat ./coverage/lcov.info | codecov
deploy:
  provider: releases
  api_key:
    secure: FbRS8IqAHbmwPSSuMaE9a2EV4Br/AIbAwFrsxKmhqMlK8Rc/irnopku+3WKYeuRud/cAqTZsPvv8h4iAik+91KVS5l9acSVpf5M8Wghz6AAxXRBjJ0NALMgqqbDypmdJZf30QCuVq0G0u6Nuxc4D7udg7o76o09fCBmP2ZahjIc=
  file:
    - "remark-github.js"
    - "remark-github.min.js"
  on:
    tags: true
