language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aUDrUzCeMiwPIJu03cd/cZNRy2JBRvVtfqntfChmmXJEb0A3UZVN4pMqOPk5iRa27I+h8oLYinbT7b4x4Ehn303kUemQeiIJgXdWVwwPXfYfSun+DdpVbNQSEv0evlKMt61SUvoAnp/oVCWrFz96a7jpy9JgZyRM8nLipG1VeOw=
  file:
    - "remark-github.js"
    - "remark-github.min.js"
  on:
    tags: true
