language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    skip_cleanup: true
    email: tituswormer@gmail.com
    api_key:
      secure: NWyqFudUi3MRx9d73d0AyNuuxxAOIzcxVUWzjnxzM5PXKfGcWoZeJzd6QYA0TENdIIf0Sjt4nMNrTFKlW/QkAE0lnRkEtT7odxi+oCxtX3MNDUDtT+Ug9/9RcDaf/lm4YF12gAKRL+qbISC2/vBIFPLGLJokyvKApWlUIBzhznk=
    on:
      tags: true
      node: '9.0'
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: FbRS8IqAHbmwPSSuMaE9a2EV4Br/AIbAwFrsxKmhqMlK8Rc/irnopku+3WKYeuRud/cAqTZsPvv8h4iAik+91KVS5l9acSVpf5M8Wghz6AAxXRBjJ0NALMgqqbDypmdJZf30QCuVq0G0u6Nuxc4D7udg7o76o09fCBmP2ZahjIc=
    file:
      - "remark-github.js"
      - "remark-github.min.js"
    on:
      tags: true
      node: '9.0'
